<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Solidary.Worker-8756c663-30ac-4687-84a6-b5aa0a0db6d0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.15.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="prometheus-net.AspNetCore" Version="8.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Solidary.Domain\Solidary.Domain.csproj" />
    <ProjectReference Include="..\Solidary.Contracts\Solidary.Contracts.csproj" />
    <ProjectReference Include="..\Solidary.Infrastructure\Solidary.Infrastructure.csproj" />
  </ItemGroup>
</Project>
