global:
  scrape_interval: 5s

scrape_configs:
  - job_name: solidary-api
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8080"]

  - job_name: solidary-worker
    metrics_path: /metrics
    static_configs:
      - targets: ["worker:8081"]
