<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Solidary.Domain\Solidary.Domain.csproj" />
    <ProjectReference Include="..\Solidary.Contracts\Solidary.Contracts.csproj" />
    <ProjectReference Include="..\Solidary.Infrastructure\Solidary.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
